# Generated by Django 4.1.3 on 2023-03-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synopsis', '0016_genre_genre_human_text_alter_genre_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='genre_human_text',
        ),
        migrations.AddField(
            model_name='genre',
            name='ght',
            field=models.CharField(default='Adventure', max_length=25, unique=True, verbose_name='Genre Human Text'),
        ),
    ]
