# Generated by Django 4.1.3 on 2023-03-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synopsis', '0013_alter_genre_genre_alter_genre_human_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='human_genre',
            field=models.CharField(max_length=25, verbose_name='human_genre'),
        ),
    ]
