# Generated by Django 4.1.3 on 2023-03-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synopsis', '0015_remove_genre_human_genre_alter_genre_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='genre_human_text',
            field=models.CharField(default='Adventure', max_length=25, unique=True, verbose_name='GHT'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(default='adventure', max_length=25, unique=True, verbose_name='Genre'),
        ),
    ]
