# Generated by Django 4.1.3 on 2023-02-16 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
