# Generated by Django 4.1.3 on 2023-03-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synopsis', '0012_genre_human_genre_alter_genre_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(max_length=25, unique=True, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='human_genre',
            field=models.CharField(max_length=25, unique=True, verbose_name='human_genre'),
        ),
    ]
