# Generated by Django 4.1.3 on 2023-02-11 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('synopsis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='Member',
        ),
    ]
