# Generated by Django 4.1.3 on 2023-02-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synopsis', '0003_remove_book_liked_by_member_liked_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(default='Adventure', max_length=10, unique=True, verbose_name='Genre'),
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
