# Generated by Django 4.1.3 on 2023-02-16 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('synopsis', '0005_book_liked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='liked_by',
        ),
    ]
