# Generated by Django 4.1.3 on 2023-02-20 13:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('synopsis', '0007_book_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='seen_by',
            field=models.ManyToManyField(blank=True, related_name='seen_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
