# Generated by Django 4.1.3 on 2023-03-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synopsis', '0009_remove_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='genre_list', to='synopsis.genre'),
        ),
    ]
