# Generated by Django 4.1.3 on 2023-03-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synopsis', '0011_book_img_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='human_genre',
            field=models.CharField(default='Adventure', max_length=25, unique=True, verbose_name='human_genre'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(default='Adventure', max_length=25, unique=True, verbose_name='Genre'),
        ),
    ]
