# Generated by Django 4.1.3 on 2023-03-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synopsis', '0018_remove_genre_ght'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='ght',
            field=models.CharField(default='Adventure', max_length=25, unique=True, verbose_name='Genre Human text'),
        ),
    ]
