# Generated by Django 4.1.3 on 2023-03-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synopsis', '0019_genre_ght'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='ght',
            field=models.CharField(default='Adventure', max_length=25, unique=True, verbose_name='Genre Human Text'),
        ),
    ]
