# Generated by Django 4.1.3 on 2023-02-16 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('synopsis', '0004_alter_genre_genre_delete_member'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0002_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=25, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=25, verbose_name='Email')),
                ('liked_books', models.ManyToManyField(blank=True, to='synopsis.book')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
