# Generated by Django 4.1.3 on 2023-02-16 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='last_name',
        ),
    ]
