# Generated by Django 4.1.7 on 2023-04-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_remove_member_email_remove_member_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='seen_instructions',
            field=models.BooleanField(default=False),
        ),
    ]
